project_id = "tslyqspazfsipytuultj"

[functions.generate-study-plan]
verify_jwt = false

[functions.scriba-chat]
verify_jwt = false

[functions.search-resources]
verify_jwt = false

[functions.ai-notes-tool]
verify_jwt = false

[functions.review-task]
verify_jwt = false

[functions.generate-flashcards]
verify_jwt = false

[functions.parse-document]
verify_jwt = false

[functions.study-hub-chat]
verify_jwt = false
